# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 10:44
from __future__ import unicode_literals

import apps.repo.validtor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='grade',
            field=models.IntegerField(choices=[(1, '入门'), (2, '简单'), (3, '中等'), (4, '困难'), (5, '超难')], null=True, validators=[apps.repo.validtor.valid_difficulty], verbose_name='题目难度'),
        ),
    ]
