# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_answerscollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerscollection',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_collection_set', to='repo.Answers', verbose_name='答题记录'),
        ),
        migrations.AlterField(
            model_name='answerscollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_collection_set', to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
    ]
