# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20180814_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer_num',
            field=models.IntegerField(default=0, verbose_name='答题人数'),
        ),
    ]
